### PR TITLE
Add a pre-processing library to enhance training speed, accuracy rate, and front-end performance.

### PR DESCRIPTION
**Pull request by scc-tw**
一個 C++ 寫成的圖片預處理
執行成效如 README （或可看 demo/*.bmp ）
https://github.com/25077667/nsysu-captcha-solver/tree/main/src/bmp_pre_proc

塗抹掉雜訊之後，肯定能夠提昇正確率
並且前處理使用 C++，效能可有效提昇。

### CODE REVIEW

**Comment by ernestchu** [comment]
Great, the result is incredible. However, for the sake of simplicity, please provide the pure python and javascript implementations and integrate them into the existing files. Since we don't care about the minor performance difference when training the network and javascript could yield adequate performance in the deployment. Thanks!

**Comment by scc-tw** [comment]
@ernestchu Hey, we add extension support for Firefox.

**Comment by ernestchu** [comment]
Please provide more details about Firefox release in the future commit. Thanks!

**Comment by scc-tw** [comment]
@OEmiliatanO Here you go.

**Pull request merged**
